name: tetris
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.9
  - aom=3.6.0
  - attr=2.5.1
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - cairo=1.16.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - expat=2.5.0
  - fluidsynth=2.3.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - gettext=0.21.1
  - graphite2=1.3.14
  - harfbuzz=7.3.0
  - icu=72.1
  - jack=1.9.22
  - lame=3.100
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libavif=0.11.1
  - libcap=2.67
  - libdb=6.2.32
  - libdeflate=1.18
  - libexpat=2.5.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libglib=2.76.4
  - libgomp=13.1.0
  - libgpg-error=1.47
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libmad=0.15.1b
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libsndfile=1.2.0
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=253
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - mpg123=1.31.3
  - mypy=0.981
  - mypy_extensions=0.4.3
  - ncurses=6.4
  - openssl=3.1.1
  - opusfile=0.12
  - pcre2=10.40
  - pip=23.1.2
  - pixman=0.40.0
  - portaudio=19.6.0
  - portmidi=2.0.4
  - psutil=5.9.0
  - pulseaudio-client=16.1
  - pygame=2.5.0
  - python=3.11.4
  - python_abi=3.11
  - readline=8.2
  - sdl2=2.26.5
  - sdl2_image=2.6.3
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.20.2
  - setuptools=67.8.0
  - tk=8.6.12
  - toml=0.10.2
  - typing_extensions=4.6.3
  - tzdata=2023c
  - wheel=0.38.4
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
